language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly

before_install:
  - sudo apt-get update
  - composer self-update

install:
  - sudo apt-get install memcached php5-memcached
  - composer install --no-interaction --prefer-source --dev
  - composer require satooshi/php-coveralls:dev-master

script:
  - phpunit --coverage-clover tests/coverage-clover.xml

after_script:
  - vendor/bin/coveralls -v
